### ISSUE TITLE
Automatic detection of LU file types

### ISSUE THREAD

**Issue by wertercatt** [Xiphoseer/assembly_rs#9]
[`file` by Ian Darwin](https://github.com/file/file) is the tool used in Linux and other open source distros to identify the types of files without relying on their extensions. It'd be useful to have a LU specific version that can correctly identify .g, .gfx, .luz and other game specific formats if their original filename is lost due to extraction from a pk without a matching trunk.txt available. file can currently identify NIF and DDS files correctly, but misinterprets hkx havok physics files as being from a project called DIY-Thermocam. Given that Assembly can already parse headers for several LU files, it seems like being able to tell what format a file is wouldn't be too far out of scope

**Comment by Xiphoseer** [comment]
I like that idea! But I think re-using the *magic* files from the `file` tool might be even better for that task. Trying whether a full parse succeeds does not seem like the best strategy with an imperfect implementation. LU has very little magic bytes for its own formats, but we can make best-effort guesses for a lot of the files, especially if they're new enough.

I just tried this:
1. save the following file somewhere (e.g. `$HOME/.magic/lu`)
2. Compile it using `file -C -m ~/.magic/lu` resulting in `~/.magic/lu.mgc`
3. Move it to `~/.magic.mgc`

Then you can detect a subset of LU files with normal `file` command on linux

```
4 lelong 0x8   LU File Database
!:ext fdb

0 string CHNK   LU Level File (modern)
!:ext lvl

0 lelong >0x23
>0 lelong <0x2a   LU Zone File
!:ext luz

## XML Files
0 string \<?xml\ version=
>0 search/400 \<LXFML\ versionMajor   LDD Model (lxfml)
!:ext lxfml
>0 search/128 \<envData>   LU Zone Environment
!:ext evc
>0 search/128 \<triggers   LU Zone Triggers
!:ext lutrigger

0 leshort 0x20   LU Terrain File
!:ext raw

0 belong 0x57e0e057
>4 belong 0x10c0c010   Havok Physics Model
!:ext hkx

0 string CFX   LU UI Widget (Scaleform / Flash)
!:ext gfx

0 lelong 80
>4 lelong 420   LU Particle Sprite Bank (forkp)
!:ext psb

0 string EMITTERNAME   LU Particle Emitter (forkp)
!:ext txt

0 string ndpk   LU Pack Archive
!:ext pk

0 string [version]   LU Patcher Manifest
!:ext txt

0 lelong 3
>8 search/50 .pk   LU Pack Index (v3)
!:ext pki

0 string 10GB LEGO Brick Geometry v1.0
!:ext g

0 regex require   LU Lua File
!:ext lua
0 regex --   LU Lua File
!:ext lua
```
